[project]
name = "blossom-music-gen"
version = "0.6.1"
requires-python = ">=3.10,<3.11"

[project.optional-dependencies]
midi = ["mido"]
diarization = ["pyannote.audio"]
tts = ["piper-tts", "soundfile"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
